lista = []
a = int(input("digite um número: "))
lista.append(a)
b = int(input("digite um número: "))
lista.append(b)
c = int(input("digite um número: "))
lista.append(c)
d = int(input("digite um número: "))
lista.append(d)
e = int(input("digite um número: "))
lista.append(e)
print(lista)