lista = []
a = int(input("digite um número: "))
lista.append(a)
b = int(input("digite um número: "))
lista.append(b)
c = int(input("digite um número: "))
lista.append(c)
d = int(input("digite um número: "))
lista.append(d)
e = int(input("digite um número: "))
lista.append(e)
lista_1 = []
a = int(input("digite um número: "))
lista_1.append(a)
b = int(input("digite um número: "))
lista_1.append(b)
c = int(input("digite um número: "))
lista_1.append(c)
d = int(input("digite um número: "))
lista_1.append(d)
e = int(input("digite um número: "))
lista_1.append(e)
lista_2 = lista + lista_1
print(lista_2)